<?php

/* custom routes generated by CRUD */
Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('notas', 'NotasController');
	Route::get('notas/{CODAVALIACAO}/{CODPARTICIPANTE}/delete', array('as' => 'admin.notas.delete', 'uses' => 'NotasController@getDelete'));
	Route::get('notas/{CODAVALIACAO}/{CODPARTICIPANTE}/confirm-delete', array('as' => 'admin.notas.confirm-delete', 'uses' => 'NotasController@getModalDelete'));
});
Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('veravaliacaos', 'VeravaliacaosController');
	Route::get('veravaliacaos/{id}/delete', array('as' => 'admin.veravaliacaos.delete', 'uses' => 'VeravaliacaosController@getDelete'));
	Route::get('veravaliacaos/{id}/confirm-delete', array('as' => 'admin.veravaliacaos.confirm-delete', 'uses' => 'VeravaliacaosController@getModalDelete'));
});
Route::group(array('prefix' => 'admin', 'middleware' => 'SentinelAdmin'), function () {Route::resource('vercargos', 'VercargosController');
	Route::get('vercargos/{id}/delete', array('as' => 'admin.vercargos.delete', 'uses' => 'VercargosController@getDelete'));
	Route::get('vercargos/{id}/confirm-delete', array('as' => 'admin.vercargos.confirm-delete', 'uses' => 'VercargosController@getModalDelete'));
});
